import { createContext, useContext, type ReactNode } from "react";

export type IconOverrideMap = Record<string, string>;
export type IconCategory =
  | "lighting"
  | "home"
  | "climate"
  | "security"
  | "apple"
  | "media"
  | "appliances"
  | "energy"
  | "outdoor";

export type IconOption = {
  key: string;
  category: IconCategory;
  it: string;
  en: string;
  keywords: string[];
};

type IconDefinition = IconOption & { glyph: ReactNode };

export const ICON_CATEGORY_ORDER: IconCategory[] = [
  "lighting",
  "home",
  "climate",
  "security",
  "apple",
  "media",
  "appliances",
  "energy",
  "outdoor",
];

const def = (
  key: string,
  category: IconCategory,
  it: string,
  en: string,
  keywords: string[],
  glyph: ReactNode,
): IconDefinition => ({ key, category, it, en, keywords, glyph });

const ICON_DEFINITIONS: IconDefinition[] = [
  // Lighting — Hue/Home-inspired semantic coverage.
  def("bulb","lighting","Lampadina","Bulb",["luce","light","bulb"],<><path d="M9.3 17.3h5.4M10.2 20h3.6M12 3.2a6.3 6.3 0 0 0-3.7 11.4c.7.5 1 1.3 1 2.2h5.4c0-.9.3-1.7 1-2.2A6.3 6.3 0 0 0 12 3.2Z"/></>),
  def("bulb-globe","lighting","Lampadina globe","Globe bulb",["globe","sfera","hue"],<><circle cx="12" cy="9.5" r="5.2"/><path d="M9.5 15h5M10 18h4M10.8 20h2.4"/></>),
  def("bulb-filament","lighting","Filamento","Filament bulb",["filament","vintage","edison"],<><path d="M8.5 14.5A5.8 5.8 0 1 1 15.5 14.5L14 17H10l-1.5-2.5ZM10 20h4M9.5 17h5"/><path d="m10 9 2 3 2-3"/></>),
  def("pendant","lighting","Sospensione","Pendant",["pendant","sospensione","lamp"],<><path d="M12 3v5M7 9h10l2 5H5l2-5ZM8 18h8"/></>),
  def("pendant-round","lighting","Sospensione tonda","Round pendant",["pendant","round"],<><path d="M12 3v5"/><path d="M7 9c0 4 2 6 5 6s5-2 5-6H7ZM9 19h6"/></>),
  def("ceiling","lighting","Plafoniera","Ceiling light",["ceiling","soffitto"],<><path d="M5 5h14M8 8h8l2 5H6l2-5ZM9 17h6"/></>),
  def("ceiling-round","lighting","Plafoniera tonda","Round ceiling",["ceiling","round"],<><path d="M7 7h10"/><ellipse cx="12" cy="12" rx="6" ry="4"/><path d="M9 18h6"/></>),
  def("chandelier","lighting","Lampadario","Chandelier",["chandelier","lampadario"],<><path d="M12 3v5M7 8h10M8 8v3M16 8v3M12 8v3M6 14h4M10 14h4M14 14h4M7 14v3M12 14v3M17 14v3"/></>),
  def("floor-lamp","lighting","Piantana","Floor lamp",["floor","piantana"],<><path d="M9 5h6l2 6H7l2-6ZM12 11v8M8.5 20h7"/></>),
  def("table-lamp","lighting","Lampada tavolo","Table lamp",["table","desk","comodino"],<><path d="M9 6h6l2 5H7l2-5ZM12 11v5M9 19h6"/></>),
  def("wall-lamp","lighting","Applique","Wall lamp",["wall","applique","sconce"],<><path d="M5 5v14M5 9h5l3 3-3 3H5M15 9v6"/></>),
  def("spotlight","lighting","Faretto","Spotlight",["spot","faretto"],<><path d="M8 5h8l1 5H7l1-5ZM12 10v3M9 17l3-4 3 4"/></>),
  def("spot-double","lighting","Doppio faretto","Double spot",["spot","double"],<><path d="M5 6h14M8 6v4M16 6v4"/><path d="m6 10 4 1-2 4-4-1 2-4ZM14 11l4-1 2 4-4 1-2-4Z"/></>),
  def("spot-triple","lighting","Triplo faretto","Triple spot",["spot","triple"],<><path d="M4 6h16M7 6v4M12 6v4M17 6v4"/><circle cx="7" cy="13" r="2"/><circle cx="12" cy="13" r="2"/><circle cx="17" cy="13" r="2"/></>),
  def("light-strip","lighting","Striscia LED","Light strip",["led","strip","lightstrip"],<><path d="M5 7h10a4 4 0 0 1 0 8H9a3 3 0 0 0 0 6"/><path d="M7 7h.01M11 7h.01M15 7h.01M18 10h.01M16 14h.01M12 15h.01"/></>),
  def("light-bar","lighting","Barra luce","Light bar",["bar","lightbar"],<><rect x="5" y="7" width="14" height="10" rx="5"/><path d="M8 12h8"/></>),
  def("gradient","lighting","Luce gradient","Gradient light",["gradient","ambient"],<><path d="M6 18V6M10 20V4M14 18V6M18 16V8"/></>),
  def("candle","lighting","Candela","Candle",["candle","candela"],<><path d="M9 10h6v10H9z"/><path d="M12 9c-2-2-1-4 0-6 1 2 2 4 0 6Z"/></>),
  def("lantern","lighting","Lanterna","Lantern",["lantern","outdoor"],<><path d="M8 8h8l2 12H6L8 8ZM9 8V5h6v3M9 12h6M10 16h4"/></>),
  def("outdoor-wall","lighting","Luce esterna","Outdoor wall light",["outdoor","wall"],<><path d="M5 4v16M5 8h7l3 4-3 4H5M15 10h4M15 14h4"/></>),

  // Home / rooms / openings.
  def("switch","home","Interruttore","Switch",["switch","relay"],<><rect x="6" y="4" width="12" height="16" rx="3"/><circle cx="12" cy="10" r="2.3"/><path d="M12 12.3V16"/></>),
  def("dimmer","home","Dimmer","Dimmer",["dimmer","rotary"],<><rect x="5" y="4" width="14" height="16" rx="3"/><circle cx="12" cy="12" r="3.2"/><path d="M12 8.8V6"/></>),
  def("outlet","home","Presa","Outlet",["presa","socket"],<><rect x="5" y="4" width="14" height="16" rx="3"/><path d="M9 9v3M15 9v3M9.5 16h5"/></>),
  def("smart-plug","home","Presa smart","Smart plug",["plug","smart","presa"],<><rect x="6" y="4" width="12" height="16" rx="4"/><path d="M9 9v3M15 9v3M9 16h6"/></>),
  def("blinds","home","Tapparella","Blinds",["cover","shutter"],<><rect x="5" y="4" width="14" height="16" rx="1.5"/><path d="M5 8h14M7 11h10M7 14h10M12 17v3"/></>),
  def("shutters","home","Persiana","Shutters",["shutter","persiana"],<><rect x="4" y="4" width="7" height="16"/><rect x="13" y="4" width="7" height="16"/><path d="M6 8h3M6 12h3M6 16h3M15 8h3M15 12h3M15 16h3"/></>),
  def("curtains","home","Tende","Curtains",["curtain","tenda"],<><path d="M5 4h14M7 5v15M17 5v15M7 8c3 2 3 6 0 9M17 8c-3 2-3 6 0 9"/></>),
  def("awning","home","Tenda da sole","Awning",["awning","tenda","sole"],<><path d="M4 6h16l-2 5H6L4 6ZM6 11v9M18 11v9M6 15h12"/></>),
  def("window","home","Finestra","Window",["window","opening"],<><rect x="4.5" y="4" width="15" height="16" rx="1.5"/><path d="M12 4v16M4.5 12h15"/></>),
  def("window-open","home","Finestra aperta","Open window",["window","open"],<><path d="M5 4h14v16H5V4ZM12 4v16M12 4l6 3v10l-6 3"/></>),
  def("door","home","Porta","Door",["door","entrance"],<><path d="M6 20V4h12v16M9 20V7h6v13M13 13h.01"/></>),
  def("door-open","home","Porta aperta","Open door",["door","open"],<><path d="M5 20V4h13v16M8 5l8 2v12l-8 1V5ZM13 13h.01"/></>),
  def("garage","home","Garage","Garage",["garage","door"],<><path d="M4 20V8l8-4 8 4v12M7 20v-9h10v9M7 14h10M7 17h10"/></>),
  def("gate","home","Cancello","Gate",["gate","cancello"],<><path d="M4 20V7M20 20V7M6 9h12v11H6V9ZM6 12h12M12 9v11"/></>),
  def("stairs","home","Scale","Stairs",["stairs","scale"],<><path d="M4 19h4v-4h4v-4h4V7h4"/></>),
  def("sofa","home","Divano","Sofa",["sofa","salotto"],<><path d="M6 11V8a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v3M5 11h14a2 2 0 0 1 2 2v5H3v-5a2 2 0 0 1 2-2ZM6 18v2M18 18v2"/></>),
  def("bed","home","Letto","Bed",["bed","camera"],<><path d="M4 19V8M20 19v-6a3 3 0 0 0-3-3H9a3 3 0 0 0-3 3v3M4 16h16M6 10V7h5v3"/></>),
  def("desk","home","Scrivania","Desk",["desk","studio"],<><path d="M4 10h16v4H4zM6 14v6M18 14v6M9 14v3h6v-3"/></>),
  def("bath","home","Vasca","Bath",["bath","vasca"],<><path d="M4 12h16v3a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4v-3ZM6 12V7a2 2 0 0 1 4 0M7 19v2M17 19v2"/></>),
  def("shower","home","Doccia","Shower",["shower","doccia"],<><path d="M6 20V8a4 4 0 0 1 8 0M14 8h4M16 11v.01M13 13v.01M18 14v.01M15 17v.01"/></>),
  def("toilet","home","WC","Toilet",["toilet","wc"],<><path d="M7 4h8v7H7V4ZM6 11h11a5 5 0 0 1-5 6H9a3 3 0 0 1-3-3v-3ZM9 17v3h6"/></>),
  def("faucet","home","Rubinetto","Faucet",["faucet","rubinetto"],<><path d="M5 10h12v5H5M9 10V7h6M12 7V4M9 4h6M17 12h2v4h-2"/></>),
  def("closet","home","Armadio","Closet",["closet","armadio"],<><rect x="5" y="4" width="14" height="16" rx="1"/><path d="M12 4v16M10 12h.01M14 12h.01"/></>),
  def("room","home","Stanza","Room",["room","home"],<><path d="m4 11 8-7 8 7v9H4v-9ZM9 20v-6h6v6"/></>),

  // Climate / air.
  def("thermometer","climate","Temperatura","Temperature",["temperature","clima"],<><path d="M14.4 14.8V5.6a2.4 2.4 0 0 0-4.8 0v9.2a4.4 4.4 0 1 0 4.8 0Z"/><path d="M12 8v8"/></>),
  def("thermostat","climate","Termostato","Thermostat",["thermostat","clima"],<><circle cx="12" cy="12" r="7"/><path d="M12 8v5l3 2M7 5l2 2M17 5l-2 2"/></>),
  def("radiator","climate","Radiatore","Radiator",["radiator","termosifone"],<><rect x="5" y="5" width="14" height="13" rx="2"/><path d="M8 7v9M12 7v9M16 7v9M7 18v2M17 18v2"/></>),
  def("floor-heat","climate","Riscaldamento a pavimento","Floor heating",["floor","heat"],<><path d="M4 17h16M5 13h14M7 9h10"/><path d="M8 6c0-1 1-1 1-2M12 7c0-1 1-1 1-2M16 6c0-1 1-1 1-2"/></>),
  def("fan","climate","Ventola","Fan",["fan","ventola"],<><circle cx="12" cy="12" r="2"/><path d="M12 10c-1-5 2-7 4-5 1.8 2-.4 5-3 6M14 12c5-1 7 2 5 4-2 1.8-5-.4-6-3M12 14c1 5-2 7-4 5-1.8-2 .4-5 3-6M10 12c-5 1-7-2-5-4 2-1.8 5 .4 6 3"/></>),
  def("ceiling-fan","climate","Ventilatore soffitto","Ceiling fan",["ceiling","fan"],<><path d="M12 3v6"/><circle cx="12" cy="11" r="2"/><path d="M10 11H4c0-2 2-3 6-2M14 11h6c0 2-2 3-6 2M12 13v7c-2 0-3-2-2-6"/></>),
  def("ac","climate","Climatizzatore","Air conditioner",["ac","air conditioner"],<><rect x="4" y="5" width="16" height="7" rx="2"/><path d="M7 9h10M8 15c0 2-2 2-2 4M12 15c0 2-2 2-2 4M16 15c0 2-2 2-2 4"/></>),
  def("snowflake","climate","Raffrescamento","Cooling",["cool","snow"],<><path d="M12 3v18M4.2 7.5l15.6 9M4.2 16.5l15.6-9M9 5l3 2 3-2M9 19l3-2 3 2"/></>),
  def("flame","climate","Riscaldamento","Heating",["heat","flame"],<><path d="M13 3c.5 3-2 4.3-1 7 1-1.5 2.8-2.3 4-4 2.2 3 3.2 5.3 2.5 8.2A6.8 6.8 0 0 1 5 13c0-3.6 2.2-6.3 5.4-9-.2 3.3 1.2 4.2 2.6 5"/></>),
  def("droplet","climate","Umidità","Humidity",["humidity","water"],<><path d="M12 3.7c3.1 4.1 5.2 6.8 5.2 9.8a5.2 5.2 0 0 1-10.4 0c0-3 2.1-5.7 5.2-9.8Z"/><path d="M9.5 14.2a2.8 2.8 0 0 0 2.7 2.1"/></>),
  def("air-purifier","climate","Purificatore aria","Air purifier",["air","purifier"],<><rect x="6" y="4" width="12" height="16" rx="3"/><circle cx="12" cy="13" r="3"/><path d="M9 8h6M10 13h4M12 11v4"/></>),
  def("air-quality","climate","Qualità aria","Air quality",["air","quality","co2"],<><circle cx="12" cy="12" r="7"/><path d="M8 14c2-4 6-4 8 0M9 9h.01M15 9h.01"/></>),
  def("humidifier","climate","Umidificatore","Humidifier",["humidifier","humidity"],<><rect x="6" y="7" width="12" height="12" rx="3"/><path d="M12 4c1 1 2 2 2 3M9 4c1 1 2 2 2 3M9 14c2-3 4-3 6 0"/></>),
  def("dehumidifier","climate","Deumidificatore","Dehumidifier",["dehumidifier","dry"],<><rect x="6" y="5" width="12" height="14" rx="3"/><path d="M9 10h6M10 14h4M12 3v2"/></>),

  // Security / sensors.
  def("sensor","security","Sensore","Sensor",["sensor","radar"],<><circle cx="12" cy="12" r="2.2"/><path d="M7.7 7.7a6.1 6.1 0 0 0 0 8.6M16.3 7.7a6.1 6.1 0 0 1 0 8.6M5 5a9.9 9.9 0 0 0 0 14M19 5a9.9 9.9 0 0 1 0 14"/></>),
  def("motion","security","Movimento","Motion",["motion","movimento"],<><circle cx="12" cy="7.5" r="2.2"/><path d="M8 20c.5-4 1.8-6.2 4-6.2s3.5 2.2 4 6M5 10a8 8 0 0 0 0 4M19 10a8 8 0 0 1 0 4"/></>),
  def("presence","security","Presenza","Presence",["presence","presenza"],<><circle cx="12" cy="8" r="2.5"/><path d="M7 19c.8-4 2.3-6 5-6s4.2 2 5 6"/></>),
  def("contact","security","Contatto","Contact sensor",["contact","door","window"],<><rect x="5" y="6" width="5" height="12" rx="1"/><rect x="14" y="7" width="5" height="10" rx="1"/><path d="M12 9v6"/></>),
  def("lock","security","Serratura","Lock",["lock","serratura"],<><rect x="6" y="10" width="12" height="10" rx="2"/><path d="M9 10V7a3 3 0 0 1 6 0v3M12 14v2"/></>),
  def("unlock","security","Serratura aperta","Unlocked",["unlock","open"],<><rect x="6" y="10" width="12" height="10" rx="2"/><path d="M9 10V7a3 3 0 0 1 5-2M12 14v2"/></>),
  def("shield","security","Sicurezza","Security",["alarm","shield"],<><path d="M12 3.5 19 6v5.3c0 4.4-2.8 7.4-7 9.2-4.2-1.8-7-4.8-7-9.2V6l7-2.5Z"/><path d="m9 12 2 2 4-4"/></>),
  def("siren","security","Sirena","Siren",["siren","alarm"],<><path d="M7 16h10l-1-7a4 4 0 0 0-8 0l-1 7ZM5 20h14M4 9H2M22 9h-2M6 4 4 2M18 4l2-2"/></>),
  def("camera","security","Telecamera","Camera",["camera","video"],<><rect x="4.5" y="6.5" width="11.5" height="11" rx="2"/><path d="m16 10 4-2.1v8.2L16 14Z"/></>),
  def("camera-dome","security","Telecamera dome","Dome camera",["camera","dome"],<><path d="M6 12a6 6 0 0 1 12 0H6ZM5 15h14M9 12a3 3 0 0 0 6 0"/></>),
  def("doorbell","security","Videocitofono","Doorbell",["doorbell","bell","citofono"],<><rect x="7" y="4" width="10" height="16" rx="3"/><circle cx="12" cy="9" r="2"/><path d="M10 15h4"/></>),
  def("smoke","security","Fumo","Smoke",["smoke","fire"],<><path d="M5 17h14M7 13c0-2 2-2 2-4s-2-2-2-4M12 13c0-2 2-2 2-4s-2-2-2-4M17 13c0-2 2-2 2-4"/></>),
  def("co","security","Monossido CO","CO detector",["co","carbon","monoxide"],<><circle cx="12" cy="12" r="7"/><path d="M10 10a2 2 0 1 0 0 4M15 10a2 2 0 1 0 0 4"/></>),
  def("leak","security","Perdita acqua","Leak sensor",["leak","water"],<><path d="M12 4c3 4 5 6 5 9a5 5 0 0 1-10 0c0-3 2-5 5-9Z"/><path d="m7 20 10-10"/></>),
  def("flood","security","Allagamento","Flood",["flood","water"],<><path d="M3 14c2 0 2 2 4 2s2-2 4-2 2 2 4 2 2-2 4-2 2 2 4 2M3 19c2 0 2 2 4 2s2-2 4-2 2 2 4 2 2-2 4-2 2 2 4 2M12 3v8"/></>),
  def("glassbreak","security","Rottura vetro","Glass break",["glass","break"],<><rect x="5" y="4" width="14" height="16"/><path d="m12 4-2 6 3 2-3 4 2 4M13 12l4-3M10 10 7-2"/></>),

  // Media / network.
  def("tv","media","Televisore","TV",["tv","television"],<><rect x="4" y="5" width="16" height="12" rx="2"/><path d="M9 21h6M12 17v4"/></>),
  def("monitor","media","Monitor","Monitor",["monitor","display"],<><rect x="4" y="4" width="16" height="12" rx="2"/><path d="M9 20h6M12 16v4"/></>),
  def("projector","media","Proiettore","Projector",["projector","cinema"],<><rect x="4" y="7" width="16" height="10" rx="2"/><circle cx="15" cy="12" r="2.5"/><path d="M7 10h3M7 14h2"/></>),
  def("speaker","media","Altoparlante","Speaker",["speaker","audio"],<><path d="M5.2 10h3.2l4.5-3.7v11.4L8.4 14H5.2Z"/><path d="M16 9.1a4.3 4.3 0 0 1 0 5.8M18.4 6.8a7.5 7.5 0 0 1 0 10.4"/></>),
  def("soundbar","media","Soundbar","Soundbar",["soundbar","audio"],<><rect x="4" y="9" width="16" height="6" rx="3"/><circle cx="8" cy="12" r="1"/><circle cx="16" cy="12" r="1"/></>),
  def("smart-speaker","media","Smart speaker","Smart speaker",["smart","speaker","voice assistant"],<><rect x="7" y="4" width="10" height="16" rx="5"/><path d="M9 8c2-2 4-2 6 0M9 12h6M10 16h4"/></>),
  def("headphones","media","Cuffie","Headphones",["headphones","audio"],<><path d="M5 13V11a7 7 0 0 1 14 0v2M5 13h3v6H6a1 1 0 0 1-1-1v-5ZM19 13h-3v6h2a1 1 0 0 0 1-1v-5Z"/></>),
  def("gamepad","media","Console","Game controller",["game","console"],<><path d="M7 8h10a4 4 0 0 1 3.5 5.8l-1.5 3a2 2 0 0 1-3 .7l-2-1.5h-4l-2 1.5a2 2 0 0 1-3-.7l-1.5-3A4 4 0 0 1 7 8Z"/><path d="M8 11v4M6 13h4M16 12h.01M18 14h.01"/></>),
  def("remote","media","Telecomando","Remote",["remote","telecomando"],<><rect x="8" y="3" width="8" height="18" rx="3"/><circle cx="12" cy="7" r="1.5"/><path d="M10 11h4M10 14h4M10 17h4"/></>),
  def("router","media","Router","Router",["router","wifi"],<><rect x="5" y="13" width="14" height="6" rx="2"/><path d="M8 13V9M16 13V9M9 8a4 4 0 0 1 6 0M11 6a2 2 0 0 1 2 0M8 16h.01M11 16h.01"/></>),
  def("music","media","Musica","Music",["music","audio"],<><path d="M9 18V7l9-2v11M9 10l9-2"/><circle cx="7" cy="18" r="2"/><circle cx="16" cy="16" r="2"/></>),
  def("microphone","media","Microfono","Microphone",["microphone","voice"],<><rect x="9" y="4" width="6" height="10" rx="3"/><path d="M6 11a6 6 0 0 0 12 0M12 17v4M9 21h6"/></>),

  // Appliances.
  def("coffee","appliances","Macchina caffè","Coffee machine",["coffee","caffe"],<><path d="M6 9h10v5a5 5 0 0 1-5 5 5 5 0 0 1-5-5V9ZM16 11h2a2 2 0 0 1 0 4h-2M8 5c0 1 1 1 1 2M12 4c0 1 1 1 1 3"/></>),
  def("kettle","appliances","Bollitore","Kettle",["kettle","bollitore"],<><path d="M8 8h8l2 10H6L8 8ZM9 8V5h6v3M18 10h2v5h-2"/></>),
  def("oven","appliances","Forno","Oven",["oven","forno"],<><rect x="5" y="4" width="14" height="16" rx="2"/><path d="M7 8h10M8 12h8v6H8zM8 6h.01M11 6h.01M14 6h.01"/></>),
  def("microwave","appliances","Microonde","Microwave",["microwave","microonde"],<><rect x="4" y="6" width="16" height="12" rx="2"/><rect x="6" y="9" width="9" height="6" rx="1"/><path d="M17 10h.01M17 14h.01"/></>),
  def("fridge","appliances","Frigorifero","Fridge",["fridge","frigo"],<><rect x="7" y="3" width="10" height="18" rx="2"/><path d="M7 11h10M14 7v2M14 14v3"/></>),
  def("dishwasher","appliances","Lavastoviglie","Dishwasher",["dishwasher","lavastoviglie"],<><rect x="6" y="4" width="12" height="16" rx="2"/><path d="M8 8h8M9 6h.01M12 6h.01M9 14c2-3 4-3 6 0M9 17h6"/></>),
  def("washer","appliances","Lavatrice","Washer",["washer","lavatrice"],<><rect x="5" y="3.5" width="14" height="17" rx="2"/><circle cx="12" cy="13" r="4"/><path d="M8 7h.01M11 7h4"/></>),
  def("dryer","appliances","Asciugatrice","Dryer",["dryer","asciugatrice"],<><rect x="5" y="3.5" width="14" height="17" rx="2"/><circle cx="12" cy="13" r="4"/><path d="M8 7h.01M11 7h4M10 12c2-2 4-1 4 1"/></>),
  def("vacuum","appliances","Aspirapolvere","Vacuum",["vacuum","aspirapolvere"],<><path d="M7 17h10l-1.5-7h-7L7 17ZM9 10V6h6v4M5 20h14"/><circle cx="9" cy="18" r="1"/><circle cx="15" cy="18" r="1"/></>),
  def("robot","appliances","Robot aspirapolvere","Robot vacuum",["robot","narwal","roborock"],<><circle cx="12" cy="12" r="7"/><path d="M8 12h8M10 9h.01M14 9h.01M9 16h6"/></>),
  def("iron","appliances","Ferro da stiro","Iron",["iron","ferro"],<><path d="M4 17h16l-3-8H9c-1 0-2 1-2 2v6M13 9V6h3l1 3"/></>),
  def("stove","appliances","Piano cottura","Cooktop",["stove","cooktop"],<><rect x="4" y="5" width="16" height="14" rx="2"/><circle cx="9" cy="10" r="2"/><circle cx="15" cy="10" r="2"/><circle cx="9" cy="15" r="2"/><circle cx="15" cy="15" r="2"/></>),
  def("hood","appliances","Cappa","Hood",["hood","cappa"],<><path d="M8 4h8l2 7H6l2-7ZM5 14h14M8 17h8M10 20h4"/></>),
  def("toaster","appliances","Tostapane","Toaster",["toaster","toast"],<><rect x="5" y="9" width="14" height="9" rx="3"/><path d="M8 9V6h8v3M17 12h2M8 18v2M16 18v2"/></>),

  // Energy.
  def("battery","energy","Batteria","Battery",["battery","batteria"],<><rect x="5" y="7" width="13" height="10" rx="2"/><path d="M18 10h2v4h-2M8 12h7"/></>),
  def("battery-charge","energy","Batteria in carica","Charging battery",["battery","charge"],<><rect x="5" y="7" width="13" height="10" rx="2"/><path d="M18 10h2v4h-2M12 9l-2 4h3l-1 3"/></>),
  def("solar","energy","Pannello solare","Solar panel",["solar","panel"],<><path d="M5 11h14l-2 8H7l-2-8ZM8 14h8M9 11l1-4h4l1 4M12 3v2M5 5l2 2M19 5l-2 2"/></>),
  def("meter","energy","Contatore","Energy meter",["meter","energy"],<><rect x="6" y="4" width="12" height="16" rx="2"/><circle cx="12" cy="11" r="3"/><path d="M12 11l2-2M9 17h6"/></>),
  def("bolt","energy","Energia","Energy",["bolt","energy","electric"],<><path d="m13 3-6 10h5l-1 8 6-11h-5l1-7Z"/></>),
  def("ev-charger","energy","Wallbox EV","EV charger",["ev","charger","wallbox"],<><rect x="6" y="4" width="10" height="16" rx="2"/><path d="m11 8-2 4h3l-1 4M16 8h2l2 2v6"/></>),
  def("generator","energy","Generatore","Generator",["generator","power"],<><rect x="4" y="7" width="16" height="10" rx="2"/><circle cx="9" cy="12" r="2.5"/><path d="M14 10h3M14 13h3M6 17v2M18 17v2"/></>),

  // Outdoor / mobility.
  def("car","outdoor","Auto","Car",["car","auto"],<><path d="m5 15 1.5-5h11L19 15v4h-2v-2H7v2H5v-4ZM8 10l1-3h6l1 3"/><circle cx="8" cy="15" r="1"/><circle cx="16" cy="15" r="1"/></>),
  def("scooter","outdoor","Monopattino","Scooter",["scooter","mobility"],<><circle cx="7" cy="18" r="2"/><circle cx="17" cy="18" r="2"/><path d="M7 18h6l3-8h3M16 10l-2-4h3M12 14H8"/></>),
  def("bike","outdoor","Bici","Bike",["bike","bici"],<><circle cx="6" cy="16" r="4"/><circle cx="18" cy="16" r="4"/><path d="m6 16 4-7 3 7M10 9h4M13 16h5M14 9l4 7"/></>),
  def("leaf","outdoor","Giardino","Garden",["leaf","garden"],<><path d="M19 4C11 4 6 8 6 14c0 3 2 5 5 5 6 0 8-7 8-15Z"/><path d="M5 20c3-6 6-9 11-12"/></>),
  def("tree","outdoor","Albero","Tree",["tree","garden"],<><path d="M12 4c-4 0-6 3-5 6-2 1-2 5 2 5h6c4 0 4-4 2-5 1-3-1-6-5-6ZM12 15v6M9 21h6"/></>),
  def("garden","outdoor","Aiuola","Flower bed",["garden","flower"],<><path d="M12 20v-8M12 13c-4 0-5-4-3-5 2-1 3 2 3 5ZM12 13c4 0 5-4 3-5-2-1-3 2-3 5ZM6 20h12"/></>),
  def("sun","outdoor","Sole","Sun",["sun","sole"],<><circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9 7 7M17 17l2.1 2.1M19.1 4.9 17 7M7 17l-2.1 2.1"/></>),
  def("rain","outdoor","Pioggia","Rain",["rain","pioggia"],<><path d="M7 15h10a4 4 0 0 0 0-8 6 6 0 0 0-11 2 3 3 0 0 0 1 6ZM8 18l-1 2M12 18l-1 2M16 18l-1 2"/></>),
  def("weather","outdoor","Meteo","Weather",["weather","meteo"],<><circle cx="9" cy="9" r="3"/><path d="M9 3V1M3 9H1M5 5 3 3M14 5l2-2"/><path d="M7 18h10a3 3 0 0 0 0-6 5 5 0 0 0-9 2 2 2 0 0 0-1 4Z"/></>),
  def("pool","outdoor","Piscina","Pool",["pool","piscina"],<><path d="M3 14c2 0 2 2 4 2s2-2 4-2 2 2 4 2 2-2 4-2 2 2 4 2M3 19c2 0 2 2 4 2s2-2 4-2 2 2 4 2 2-2 4-2 2 2 4 2M7 14V7h4M7 10h4"/></>),
  def("sprinkler","outdoor","Irrigazione","Sprinkler",["sprinkler","irrigation"],<><path d="M12 20v-8M8 12h8M6 9l-3-2M18 9l3-2M9 7 7-3M15 7l-7-3"/></>),
  def("patio","outdoor","Patio","Patio",["patio","terrace"],<><path d="M4 10h16M6 10l2-5h8l2 5M7 10v10M17 10v10M10 15h4M10 20v-5M14 20v-5"/></>),
  def("grill","outdoor","Barbecue","Grill",["grill","bbq"],<><path d="M6 9h12a6 6 0 0 1-12 0ZM9 15l-2 6M15 15l2 6M8 21h8M9 6h6"/></>),
];


const EXTENDED_ICON_DEFINITIONS: IconDefinition[] = [
  // Apple ecosystem / personal devices — original project silhouettes.
  def("apple-tv","apple","Apple TV","Apple TV",["apple","tv","streaming","set top"],<><rect x="4" y="7" width="16" height="10" rx="3"/><path d="M8 12h.01M11 12h6M9 19h6"/></>),
  def("apple-tv-remote","apple","Telecomando Apple TV","Apple TV Remote",["apple","remote","siri"],<><rect x="9" y="3" width="6" height="18" rx="3"/><circle cx="12" cy="7" r="1.6"/><path d="M10.5 11h3M10.5 14h3M12 17h.01"/></>),
  def("homepod","apple","HomePod","HomePod",["apple","homepod","speaker"],<><rect x="7" y="3" width="10" height="18" rx="5"/><ellipse cx="12" cy="6.5" rx="3.2" ry="1.5"/><path d="M9 11c2-1.4 4-1.4 6 0M9 15c2 1.4 4 1.4 6 0"/></>),
  def("homepod-mini","apple","HomePod mini","HomePod mini",["apple","homepod","mini","speaker"],<><path d="M6 11c0-4 2.5-7 6-7s6 3 6 7v4c0 3-2.5 5-6 5s-6-2-6-5v-4Z"/><ellipse cx="12" cy="8" rx="3.4" ry="1.6"/></>),
  def("iphone","apple","iPhone","iPhone",["apple","iphone","phone"],<><rect x="7" y="2.5" width="10" height="19" rx="3"/><path d="M10 5h4M11 19h2"/></>),
  def("iphone-pro","apple","iPhone Pro","iPhone Pro",["apple","iphone","pro","phone"],<><rect x="7" y="2.5" width="10" height="19" rx="3"/><circle cx="10" cy="6" r="1"/><circle cx="13" cy="6" r="1"/><circle cx="10" cy="9" r="1"/></>),
  def("iphone-landscape","apple","iPhone orizzontale","iPhone landscape",["apple","iphone","landscape"],<><rect x="3" y="7" width="18" height="10" rx="3"/><path d="M6 10v4M18 11h.01"/></>),
  def("ipad","apple","iPad","iPad",["apple","ipad","tablet"],<><rect x="5" y="2.5" width="14" height="19" rx="2.5"/><path d="M11 5h2M11.5 19h1"/></>),
  def("ipad-mini","apple","iPad mini","iPad mini",["apple","ipad","mini","tablet"],<><rect x="6" y="3" width="12" height="18" rx="2.5"/><path d="M11 5h2M11.5 19h1"/></>),
  def("ipad-pro","apple","iPad Pro","iPad Pro",["apple","ipad","pro","tablet"],<><rect x="4.5" y="2.5" width="15" height="19" rx="2.3"/><circle cx="7.5" cy="5.5" r=".8"/><circle cx="10" cy="5.5" r=".8"/></>),
  def("macbook","apple","MacBook","MacBook",["apple","macbook","laptop"],<><rect x="5" y="4" width="14" height="10" rx="1.5"/><path d="M3 18h18l-2 2H5l-2-2Z"/></>),
  def("macbook-pro","apple","MacBook Pro","MacBook Pro",["apple","macbook","pro","laptop"],<><rect x="4" y="3.5" width="16" height="11" rx="1.5"/><path d="M2.5 18h19l-2 2h-15l-2-2ZM9 17h6"/></>),
  def("imac","apple","iMac","iMac",["apple","imac","desktop"],<><rect x="3.5" y="3.5" width="17" height="12" rx="2"/><path d="M12 15.5v4M8.5 20h7"/></>),
  def("mac-mini","apple","Mac mini","Mac mini",["apple","mac","mini","computer"],<><rect x="5" y="7" width="14" height="10" rx="2.5"/><path d="M8 10h8M17 14h.01"/></>),
  def("mac-studio","apple","Mac Studio","Mac Studio",["apple","mac","studio","computer"],<><rect x="5" y="5" width="14" height="14" rx="3"/><path d="M8 9h8M8 12h8M16.5 16h.01"/></>),
  def("studio-display","apple","Studio Display","Studio Display",["apple","display","monitor"],<><rect x="3" y="4" width="18" height="12" rx="2"/><path d="M12 16v4M8 20h8"/></>),
  def("apple-watch","apple","Apple Watch","Apple Watch",["apple","watch","wearable"],<><rect x="7" y="6" width="10" height="12" rx="3"/><path d="M9 6 10 2h4l1 4M9 18l1 4h4l1-4M18 10h1v3h-1"/></>),
  def("airpods","apple","AirPods","AirPods",["apple","airpods","earbuds"],<><path d="M8 5a3 3 0 0 0 0 6v7a2 2 0 0 0 2 2M16 5a3 3 0 0 1 0 6v7a2 2 0 0 1-2 2"/><path d="M8 8h2M14 8h2"/></>),
  def("airpods-pro","apple","AirPods Pro","AirPods Pro",["apple","airpods","pro","earbuds"],<><path d="M7 6a3 3 0 1 0 4 3v8a2 2 0 0 1-2 2M17 6a3 3 0 1 1-4 3v8a2 2 0 0 0 2 2"/><path d="M7 7h3M14 7h3"/></>),
  def("airpods-max","apple","AirPods Max","AirPods Max",["apple","airpods","max","headphones"],<><path d="M5 13v-2a7 7 0 0 1 14 0v2M5 12h4v7H7a2 2 0 0 1-2-2v-5ZM19 12h-4v7h2a2 2 0 0 0 2-2v-5Z"/></>),
  def("airtag","apple","AirTag","AirTag",["apple","airtag","tracker"],<><circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="3"/><path d="M12 5v2M12 17v2M5 12h2M17 12h2"/></>),
  def("airplay","apple","AirPlay","AirPlay",["apple","airplay","cast"],<><rect x="4" y="4" width="16" height="12" rx="2"/><path d="m8 20 4-5 4 5H8Z"/></>),
  def("vision-pro","apple","Vision Pro","Vision Pro",["apple","vision","headset","xr"],<><path d="M4 10c0-3 2-5 5-5h6c3 0 5 2 5 5v3c0 2-1.5 4-3.5 4-2.5 0-2.5-3-4.5-3s-2 3-4.5 3C5.5 17 4 15 4 13v-3Z"/><path d="M7 10h3M14 10h3"/></>),
  def("magsafe","apple","MagSafe","MagSafe",["apple","magsafe","charger"],<><circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="4"/><path d="M12 5V3M12 21v-2"/></>),
  def("apple-pencil","apple","Apple Pencil","Apple Pencil",["apple","pencil","stylus"],<><path d="m5 18 2-5 9-9 4 4-9 9-6 1ZM14 6l4 4M5 18l4-1"/></>),

  // More Apple hardware silhouettes — project-original iOS-style line glyphs.
  def("iphone-se","apple","iPhone SE","iPhone SE",["apple","iphone","se"],<><rect x="7" y="2.5" width="10" height="19" rx="2.7"/><path d="M10 5h4"/><circle cx="12" cy="18.5" r=".8"/></>),
  def("iphone-air","apple","iPhone Air","iPhone Air",["apple","iphone","air","thin"],<><rect x="8" y="2.5" width="8" height="19" rx="2.7"/><path d="M10 5h4M11 19h2"/></>),
  def("iphone-pro-max","apple","iPhone Pro Max","iPhone Pro Max",["apple","iphone","pro","max"],<><rect x="6.5" y="2.5" width="11" height="19" rx="3"/><circle cx="9.5" cy="6" r="1"/><circle cx="12.5" cy="6" r="1"/><circle cx="9.5" cy="9" r="1"/><path d="M11 19h2"/></>),
  def("iphone-standby","apple","iPhone StandBy","iPhone StandBy",["apple","iphone","standby","landscape"],<><rect x="3" y="7" width="18" height="10" rx="3"/><circle cx="9" cy="12" r="2.4"/><path d="M9 10.5V12l1 1M14 10h4M14 13h3"/></>),
  def("ipad-keyboard","apple","iPad con tastiera","iPad with keyboard",["apple","ipad","keyboard","magic keyboard"],<><rect x="5" y="3" width="14" height="12" rx="2"/><path d="M4 18h16l-1.5 2h-13L4 18ZM8 17h8"/></>),
  def("mac-pro-tower","apple","Mac Pro tower","Mac Pro tower",["apple","mac","pro","tower"],<><rect x="7" y="3" width="10" height="18" rx="2"/><circle cx="10" cy="7" r=".7"/><circle cx="14" cy="7" r=".7"/><circle cx="10" cy="11" r=".7"/><circle cx="14" cy="11" r=".7"/><path d="M9 18h6"/></>),
  def("pro-display-xdr","apple","Pro Display XDR","Pro Display XDR",["apple","display","xdr","monitor"],<><rect x="3" y="3.5" width="18" height="12" rx="2"/><path d="M12 15.5v4M8 20h8M7 7h10M7 10h10"/></>),
  def("magic-keyboard","apple","Magic Keyboard","Magic Keyboard",["apple","magic","keyboard"],<><rect x="3" y="7" width="18" height="10" rx="2"/><path d="M6 10h1M9 10h1M12 10h1M15 10h1M18 10h.01M6 13h1M9 13h1M12 13h1M15 13h3"/></>),
  def("magic-mouse","apple","Magic Mouse","Magic Mouse",["apple","magic","mouse"],<><rect x="8" y="3" width="8" height="18" rx="4"/><path d="M12 3v7M9 10h6"/></>),
  def("magic-trackpad","apple","Magic Trackpad","Magic Trackpad",["apple","magic","trackpad"],<><path d="M5 6h14l2 12H3L5 6Z"/><path d="M7 9h10"/></>),
  def("apple-watch-ultra-hardware","apple","Apple Watch Ultra","Apple Watch Ultra",["apple","watch","ultra","wearable"],<><rect x="6.5" y="6" width="11" height="12" rx="3"/><path d="M9 6 10 2h4l1 4M9 18l1 4h4l1-4M18 9h2v4h-2M9 11h6M9 14h4"/></>),
  def("apple-watch-charger","apple","Caricatore Apple Watch","Apple Watch charger",["apple","watch","charger","puck"],<><circle cx="10" cy="12" r="5"/><path d="M15 12h2a3 3 0 0 1 3 3v4M8 10h4M10 8v4"/></>),
  def("airpods-case-hardware","apple","Custodia AirPods","AirPods case",["apple","airpods","case"],<><rect x="5" y="6" width="14" height="13" rx="5"/><path d="M5 11h14M9 9h.01M15 9h.01M11 16h2"/></>),
  def("airpods-pro-case-hardware","apple","Custodia AirPods Pro","AirPods Pro case",["apple","airpods","pro","case"],<><rect x="4" y="7" width="16" height="11" rx="4"/><path d="M4 11h16M8 9h2M14 9h2M11 15h2"/></>),
  def("homepod-pair","apple","Coppia HomePod","HomePod pair",["apple","homepod","pair","stereo"],<><rect x="4" y="6" width="7" height="14" rx="3.5"/><rect x="13" y="6" width="7" height="14" rx="3.5"/><path d="M6 10h3M15 10h3"/></>),
  def("airtag-loop","apple","AirTag con loop","AirTag loop",["apple","airtag","loop","tracker"],<><circle cx="11" cy="12" r="5"/><circle cx="11" cy="12" r="2"/><path d="M15 8c4-3 6 0 4 3l-3 4"/></>),
  def("magsafe-battery","apple","Batteria MagSafe","MagSafe battery",["apple","magsafe","battery"],<><rect x="6" y="3" width="12" height="18" rx="3"/><circle cx="12" cy="10" r="4"/><path d="M10 17h4"/></>),
  def("magsafe-stand","apple","Supporto MagSafe","MagSafe stand",["apple","magsafe","stand","charger"],<><circle cx="12" cy="8" r="5"/><path d="M12 13v5M8 20h8"/></>),
  def("apple-pencil-pro","apple","Apple Pencil Pro","Apple Pencil Pro",["apple","pencil","pro","stylus"],<><path d="m5 19 2-5 9-9 3 3-9 9-5 2ZM14 7l3 3M9 14l2 2M17 4l3 3"/></>),
  def("usb-c-adapter","apple","Adattatore USB-C","USB-C adapter",["apple","usb-c","adapter","dongle"],<><rect x="4" y="8" width="8" height="8" rx="2"/><path d="M12 12h4M16 9v6M18 9h2v6h-2"/></>),
  def("airport-router","apple","AirPort","AirPort",["apple","airport","router","wifi"],<><rect x="5" y="6" width="14" height="12" rx="3"/><path d="M8 13a5 5 0 0 1 8 0M10 15a2.5 2.5 0 0 1 4 0M12 17h.01"/></>),
  def("time-capsule","apple","Time Capsule","Time Capsule",["apple","time capsule","backup","router"],<><rect x="5" y="5" width="14" height="14" rx="3"/><circle cx="12" cy="12" r="4"/><path d="M12 9v3l2 1"/></>),
  def("apple-device-stack","apple","Dispositivi Apple","Apple devices",["apple","devices","ecosystem"],<><rect x="3" y="5" width="13" height="9" rx="1.5"/><path d="M9.5 14v4M6 19h7"/><rect x="15" y="8" width="6" height="12" rx="2"/></>),
  def("airdrop-device","apple","AirDrop","AirDrop",["apple","airdrop","share"],<><rect x="8" y="5" width="8" height="14" rx="2"/><path d="M6 9a8 8 0 0 0 0 6M4 7a11 11 0 0 0 0 10M18 9a8 8 0 0 1 0 6M20 7a11 11 0 0 1 0 10"/></>),
  def("carplay-device","apple","CarPlay","CarPlay",["apple","carplay","car","iphone"],<><path d="M4 14 6 9h12l2 5v5h-2v-2H6v2H4v-5Z"/><rect x="9" y="4" width="6" height="9" rx="1.5"/></>),

  // Dedicated room silhouettes for room-level customization.
  def("room-living","home","Soggiorno","Living room",["room","living","salotto"],<><path d="M5 12h14a2 2 0 0 1 2 2v4H3v-4a2 2 0 0 1 2-2ZM6 12V9a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v3M6 18v2M18 18v2"/></>),
  def("room-kitchen","home","Cucina","Kitchen",["room","kitchen","cucina"],<><path d="M5 5h14v15H5V5ZM5 10h14M9 5v5M15 5v5M8 14h3M14 14h2M8 17h8"/></>),
  def("room-dining","home","Sala da pranzo","Dining room",["room","dining","pranzo"],<><path d="M5 11h14v4H5zM7 15v5M17 15v5M9 8h6M10 5h4"/></>),
  def("room-bedroom","home","Camera da letto","Bedroom",["room","bedroom","camera"],<><path d="M4 19v-8M20 19v-5a3 3 0 0 0-3-3H9a3 3 0 0 0-3 3v2h14M6 11V7h5a2 2 0 0 1 2 2v2"/></>),
  def("room-kids","home","Cameretta","Kids room",["room","kids","cameretta"],<><circle cx="12" cy="11" r="5"/><path d="M8 7 6 5M16 7l2-2M9.5 11h.01M14.5 11h.01M10 14h4M7 20h10"/></>),
  def("room-nursery","home","Nursery","Nursery",["room","nursery","baby"],<><path d="M6 13a6 6 0 0 1 12 0v4H6v-4ZM12 7V4M9 4h6M8 17v3M16 17v3"/></>),
  def("room-office","home","Studio","Office",["room","office","studio"],<><path d="M4 10h16v4H4zM6 14v6M18 14v6M9 14v3h6v-3M9 6h6v4"/></>),
  def("room-hallway","home","Corridoio","Hallway",["room","hallway","corridoio"],<><path d="M5 20V4h14v16M9 20V8h6v12M12 13h.01"/></>),
  def("room-entry","home","Ingresso","Entryway",["room","entry","ingresso"],<><path d="M6 20V4h12v16M9 20V7h6v13M13 13h.01M3 20h18"/></>),
  def("room-bathroom","home","Bagno","Bathroom",["room","bathroom","bagno"],<><path d="M4 12h16v3a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5v-3ZM7 12V7a3 3 0 0 1 6 0M6 20v1M18 20v1"/></>),
  def("room-laundry","home","Lavanderia","Laundry room",["room","laundry","lavanderia"],<><rect x="6" y="4" width="12" height="16" rx="2"/><circle cx="12" cy="13" r="4"/><path d="M8 7h.01M11 7h4"/></>),
  def("room-utility","home","Locale tecnico","Utility room",["room","utility","tecnico"],<><path d="M5 5h14v14H5V5ZM8 9h8M8 13h3M14 13h2M8 16h8"/></>),
  def("room-pantry","home","Dispensa","Pantry",["room","pantry","dispensa"],<><rect x="6" y="4" width="12" height="16" rx="1"/><path d="M6 9h12M6 14h12M9 7h.01M15 12h.01M10 17h4"/></>),
  def("room-wardrobe","home","Cabina armadio","Wardrobe",["room","wardrobe","armadio"],<><rect x="5" y="4" width="14" height="16" rx="1"/><path d="M12 4v16M9 9h.01M15 9h.01M8 16h8"/></>),
  def("room-balcony","home","Balcone","Balcony",["room","balcony","balcone"],<><path d="M5 4h14v9H5V4ZM3 16h18M5 16v4M9 16v4M15 16v4M19 16v4"/></>),
  def("room-terrace","home","Terrazzo","Terrace",["room","terrace","terrazzo"],<><path d="M4 17h16M6 17v3M18 17v3M8 13a4 4 0 0 1 8 0M12 3v3M5 6l2 2M19 6l-2 2"/></>),
  def("room-garden","home","Giardino","Garden room",["room","garden","giardino"],<><path d="M12 20v-8M12 13c-4 0-5-4-3-5 2-1 3 2 3 5ZM12 13c4 0 5-4 3-5-2-1-3 2-3 5ZM5 20h14"/></>),
  def("room-garage","home","Garage","Garage",["room","garage"],<><path d="M4 20V8l8-4 8 4v12M7 20v-9h10v9M7 14h10M7 17h10"/></>),
  def("room-cinema","home","Cinema","Cinema room",["room","cinema","movie"],<><rect x="4" y="5" width="16" height="12" rx="2"/><path d="m10 9 5 2.5-5 2.5V9ZM8 21h8M12 17v4"/></>),
  def("room-gym","home","Palestra","Gym",["room","gym","palestra"],<><path d="M4 10v4M7 8v8M17 8v8M20 10v4M7 12h10"/></>),
  def("room-play","home","Sala giochi","Playroom",["room","playroom","game"],<><rect x="5" y="6" width="14" height="12" rx="4"/><path d="M8 10v4M6 12h4M15 11h.01M17 13h.01"/></>),
  def("room-basement","home","Cantina","Basement",["room","basement","cantina"],<><path d="M5 20V8h14v12M4 8h16M8 12h8M8 16h8"/></>),
  def("room-attic","home","Mansarda","Attic",["room","attic","mansarda"],<><path d="m4 12 8-8 8 8M6 10v10h12V10M10 14h4v6"/></>),
  def("room-guest","home","Camera ospiti","Guest room",["room","guest","ospiti"],<><path d="M4 19v-8M20 19v-5a3 3 0 0 0-3-3H9a3 3 0 0 0-3 3v2h14M6 11V7h5M16 6h4M18 4v4"/></>),
  def("room-open-space","home","Open space","Open space",["room","open space","living"],<><path d="M4 15v-3a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3M5 15h14v5H5zM7 10V7h4v3M13 10V6h4v4"/></>),
  def("room-stairs","home","Scale","Stairs",["room","stairs","scale"],<><path d="M4 19h4v-4h4v-4h4V7h4M5 5h6"/></>),
];

const SOURCE_ICON_DEFINITIONS: IconDefinition[] = [...ICON_DEFINITIONS, ...EXTENDED_ICON_DEFINITIONS];

const aliasDef = (
  key: string,
  sourceKey: string,
  category: IconCategory,
  it: string,
  en: string,
  keywords: string[],
): IconDefinition => {
  const source = SOURCE_ICON_DEFINITIONS.find((item) => item.key === sourceKey);
  if (!source) throw new Error(`Unknown icon source: ${sourceKey}`);
  return def(key, category, it, en, keywords, source.glyph);
};

const SEMANTIC_ICON_DEFINITIONS: IconDefinition[] = [

  aliasDef("hue-white","bulb","lighting","Hue White","Hue White",["hue","white","lampadina"]),
  aliasDef("hue-white-ambiance","bulb","lighting","Hue White Ambiance","Hue White Ambiance",["hue","ambiance"]),
  aliasDef("hue-color-ambiance","bulb-globe","lighting","Hue Color Ambiance","Hue Color Ambiance",["hue","color"]),
  aliasDef("hue-e27","bulb","lighting","Hue E27","Hue E27",["hue","e27"]),
  aliasDef("hue-e14","bulb-filament","lighting","Hue E14","Hue E14",["hue","e14"]),
  aliasDef("hue-gu10","spotlight","lighting","Hue GU10","Hue GU10",["hue","gu10","spot"]),
  aliasDef("hue-mr16","spotlight","lighting","Hue MR16","Hue MR16",["hue","mr16","spot"]),
  aliasDef("hue-filament-a60","bulb-filament","lighting","Hue Filament A60","Hue Filament A60",["hue","filament","a60"]),
  aliasDef("hue-filament-g93","bulb-globe","lighting","Hue Filament G93","Hue Filament G93",["hue","filament","globe"]),
  aliasDef("hue-filament-st64","bulb-filament","lighting","Hue Filament ST64","Hue Filament ST64",["hue","filament","vintage"]),
  aliasDef("hue-candle","candle","lighting","Hue Candle","Hue Candle",["hue","candle"]),
  aliasDef("hue-luster","bulb-globe","lighting","Hue Luster","Hue Luster",["hue","luster"]),
  aliasDef("hue-go","light-bar","lighting","Hue Go","Hue Go",["hue","go","portable"]),
  aliasDef("hue-iris","bulb-globe","lighting","Hue Iris","Hue Iris",["hue","iris"]),
  aliasDef("hue-bloom","bulb-globe","lighting","Hue Bloom","Hue Bloom",["hue","bloom"]),
  aliasDef("hue-signe-floor","floor-lamp","lighting","Hue Signe piantana","Hue Signe floor",["hue","signe","floor"]),
  aliasDef("hue-signe-table","table-lamp","lighting","Hue Signe tavolo","Hue Signe table",["hue","signe","table"]),
  aliasDef("hue-play","light-bar","lighting","Hue Play","Hue Play",["hue","play","bar"]),
  aliasDef("hue-play-gradient","gradient","lighting","Hue Play Gradient","Hue Play Gradient",["hue","gradient"]),
  aliasDef("hue-lightstrip-plus","light-strip","lighting","Hue Lightstrip Plus","Hue Lightstrip Plus",["hue","strip"]),
  aliasDef("hue-solo-strip","light-strip","lighting","Hue Solo Lightstrip","Hue Solo Lightstrip",["hue","solo","strip"]),
  aliasDef("hue-centuris","spot-double","lighting","Hue Centris","Hue Centris",["hue","centris"]),
  aliasDef("hue-aurelle","ceiling","lighting","Hue Aurelle","Hue Aurelle",["hue","panel"]),
  aliasDef("hue-being","ceiling-round","lighting","Hue Being","Hue Being",["hue","ceiling"]),
  aliasDef("hue-infuse","ceiling-round","lighting","Hue Infuse","Hue Infuse",["hue","ceiling"]),
  aliasDef("hue-fair","pendant-round","lighting","Hue Fair","Hue Fair",["hue","pendant"]),
  aliasDef("hue-ensys","pendant","lighting","Hue Ensis","Hue Ensis",["hue","pendant"]),
  aliasDef("hue-adore","wall-lamp","lighting","Hue Adore","Hue Adore",["hue","bathroom"]),
  aliasDef("hue-dymera","wall-lamp","lighting","Hue Dymera","Hue Dymera",["hue","wall"]),
  aliasDef("hue-resonate","outdoor-wall","lighting","Hue Resonate","Hue Resonate",["hue","outdoor"]),
  aliasDef("hue-appear","outdoor-wall","lighting","Hue Appear","Hue Appear",["hue","outdoor"]),
  aliasDef("hue-impress","lantern","lighting","Hue Impress","Hue Impress",["hue","outdoor"]),
  aliasDef("hue-econic","lantern","lighting","Hue Econic","Hue Econic",["hue","outdoor"]),
  aliasDef("hue-calla","lantern","lighting","Hue Calla","Hue Calla",["hue","outdoor"]),
  aliasDef("hue-lily","spotlight","lighting","Hue Lily","Hue Lily",["hue","garden","spot"]),
  aliasDef("hue-discover","outdoor-wall","lighting","Hue Discover","Hue Discover",["hue","floodlight"]),
  aliasDef("hue-welcome","outdoor-wall","lighting","Hue Welcome","Hue Welcome",["hue","floodlight"]),
  aliasDef("downlight","ceiling-round","lighting","Downlight","Downlight",["recessed","incasso"]),
  aliasDef("recessed-light","spotlight","lighting","Faretto incasso","Recessed light",["incasso","spot"]),
  aliasDef("track-light","spot-triple","lighting","Binario faretti","Track light",["track","rail"]),
  aliasDef("cabinet-light","light-bar","lighting","Luce sottopensile","Cabinet light",["cabinet","kitchen"]),
  aliasDef("picture-light","wall-lamp","lighting","Luce quadro","Picture light",["picture","wall"]),
  aliasDef("bollard-light","lantern","lighting","Paletto luminoso","Bollard light",["bollard","garden"]),
  aliasDef("path-light","lantern","lighting","Luce vialetto","Path light",["path","garden"]),
  aliasDef("wall-washer","outdoor-wall","lighting","Wall washer","Wall washer",["wall","washer","light"]),
  aliasDef("neon-flex","light-strip","lighting","Neon Flex","Neon Flex",["neon","strip"]),
  aliasDef("tube-light","light-bar","lighting","Tubo luce","Tube light",["tube","linear"]),
  aliasDef("panel-light","ceiling","lighting","Pannello LED","LED panel",["panel","led"]),
  aliasDef("cluster-pendant","chandelier","lighting","Sospensione multipla","Cluster pendant",["cluster","pendant"]),
  aliasDef("apple-tv-4k","apple-tv","apple","Apple TV 4K","Apple TV 4K",["apple","tv","4k"]),
  aliasDef("apple-tv-hd","apple-tv","apple","Apple TV HD","Apple TV HD",["apple","tv","hd"]),
  aliasDef("siri-remote","apple-tv-remote","apple","Siri Remote","Siri Remote",["apple","siri","remote"]),
  aliasDef("iphone-mini","iphone","apple","iPhone mini","iPhone mini",["apple","iphone","mini"]),
  aliasDef("iphone-plus","iphone","apple","iPhone Plus","iPhone Plus",["apple","iphone","plus"]),
  aliasDef("iphone-max","iphone-pro","apple","iPhone Pro Max","iPhone Pro Max",["apple","iphone","max"]),
  aliasDef("ipad-air","ipad","apple","iPad Air","iPad Air",["apple","ipad","air"]),
  aliasDef("ipad-air-13","ipad-pro","apple","iPad Air 13","iPad Air 13",["apple","ipad","13"]),
  aliasDef("ipad-pro-11","ipad-pro","apple","iPad Pro 11","iPad Pro 11",["apple","ipad","pro","11"]),
  aliasDef("ipad-pro-13","ipad-pro","apple","iPad Pro 13","iPad Pro 13",["apple","ipad","pro","13"]),
  aliasDef("macbook-air","macbook","apple","MacBook Air","MacBook Air",["apple","macbook","air"]),
  aliasDef("macbook-pro-14","macbook-pro","apple","MacBook Pro 14","MacBook Pro 14",["apple","macbook","14"]),
  aliasDef("macbook-pro-16","macbook-pro","apple","MacBook Pro 16","MacBook Pro 16",["apple","macbook","16"]),
  aliasDef("imac-24","imac","apple","iMac 24","iMac 24",["apple","imac","24"]),
  aliasDef("mac-pro","mac-studio","apple","Mac Pro","Mac Pro",["apple","mac","pro"]),
  aliasDef("apple-watch-ultra","apple-watch","apple","Apple Watch Ultra","Apple Watch Ultra",["apple","watch","ultra"]),
  aliasDef("apple-watch-series","apple-watch","apple","Apple Watch Series","Apple Watch Series",["apple","watch","series"]),
  aliasDef("airpods-case","airpods","apple","Custodia AirPods","AirPods case",["apple","airpods","case"]),
  aliasDef("airpods-pro-case","airpods-pro","apple","Custodia AirPods Pro","AirPods Pro case",["apple","airpods","case"]),
  aliasDef("airplay-speaker","airplay","apple","Speaker AirPlay","AirPlay speaker",["apple","airplay","speaker"]),
  aliasDef("airplay-tv","airplay","apple","TV AirPlay","AirPlay TV",["apple","airplay","tv"]),
  aliasDef("smart-hub","router","media","Hub smart home","Smart home hub",["hub","bridge","home"]),
  aliasDef("matter-hub","router","media","Hub Matter","Matter hub",["matter","hub"]),
  aliasDef("thread-border-router","router","media","Thread Border Router","Thread Border Router",["thread","router"]),
  aliasDef("zigbee-bridge","router","media","Bridge Zigbee","Zigbee bridge",["zigbee","bridge"]),
  aliasDef("hue-bridge","router","media","Hue Bridge","Hue Bridge",["hue","bridge"]),
  aliasDef("streaming-box","apple-tv","media","Box streaming","Streaming box",["streaming","box"]),
  aliasDef("set-top-box","apple-tv","media","Decoder TV","Set-top box",["decoder","tv"]),
  aliasDef("media-receiver","soundbar","media","Ricevitore AV","AV receiver",["receiver","avr"]),
  aliasDef("amplifier","speaker","media","Amplificatore","Amplifier",["amp","audio"]),
  aliasDef("subwoofer","speaker","media","Subwoofer","Subwoofer",["subwoofer","audio"]),
  aliasDef("turntable","music","media","Giradischi","Turntable",["vinyl","turntable"]),
  aliasDef("radio","speaker","media","Radio","Radio",["radio","audio"]),
  aliasDef("smart-display","studio-display","media","Smart display","Smart display",["display","assistant"]),
  aliasDef("nas","router","media","NAS","NAS",["nas","server","storage"]),
  aliasDef("home-server","router","media","Home server","Home server",["server","home"]),
  aliasDef("printer","studio-display","media","Stampante","Printer",["printer","stampante"]),
  aliasDef("scanner","studio-display","media","Scanner","Scanner",["scanner"]),
  aliasDef("game-console","gamepad","media","Console giochi","Game console",["gaming","console"]),
  aliasDef("handheld-console","gamepad","media","Console portatile","Handheld console",["gaming","handheld"]),
  aliasDef("room-salon","room-living","home","Salotto","Lounge",["room","salotto"]),
  aliasDef("room-family","room-living","home","Family room","Family room",["room","family"]),
  aliasDef("room-breakfast","room-dining","home","Zona colazione","Breakfast room",["room","breakfast"]),
  aliasDef("room-master-bedroom","room-bedroom","home","Camera matrimoniale","Master bedroom",["room","master"]),
  aliasDef("room-single-bedroom","room-bedroom","home","Camera singola","Single bedroom",["room","single"]),
  aliasDef("room-baby","room-nursery","home","Stanza bimbo","Baby room",["room","baby"]),
  aliasDef("room-study","room-office","home","Studio lavoro","Study",["room","study"]),
  aliasDef("room-library","room-office","home","Biblioteca","Library",["room","library"]),
  aliasDef("room-mudroom","room-entry","home","Mudroom","Mudroom",["room","entry"]),
  aliasDef("room-corridor","room-hallway","home","Disimpegno","Corridor",["room","corridoio"]),
  aliasDef("room-powder","room-bathroom","home","Bagno ospiti","Powder room",["room","wc"]),
  aliasDef("room-spa","room-bathroom","home","Spa","Spa",["room","spa"]),
  aliasDef("room-closet","room-wardrobe","home","Armadio","Closet",["room","closet"]),
  aliasDef("room-storage","room-pantry","home","Ripostiglio","Storage room",["room","storage"]),
  aliasDef("room-server","room-utility","home","Locale server","Server room",["room","server"]),
  aliasDef("room-boiler","room-utility","home","Locale caldaia","Boiler room",["room","boiler"]),
  aliasDef("room-workshop","room-utility","home","Laboratorio","Workshop",["room","workshop"]),
  aliasDef("room-veranda","room-terrace","home","Veranda","Veranda",["room","veranda"]),
  aliasDef("room-patio","room-terrace","home","Patio","Patio",["room","patio"]),
  aliasDef("room-rooftop","room-terrace","home","Terrazza rooftop","Rooftop",["room","rooftop"]),
  aliasDef("room-greenhouse","room-garden","home","Serra","Greenhouse",["room","greenhouse"]),
  aliasDef("room-pool","pool","home","Piscina","Pool room",["room","pool"]),
  aliasDef("room-home-theater","room-cinema","home","Home theater","Home theater",["room","theater"]),
  aliasDef("room-music","music","home","Sala musica","Music room",["room","music"]),
  aliasDef("room-yoga","room-gym","home","Yoga room","Yoga room",["room","yoga"]),
  aliasDef("room-fitness","room-gym","home","Fitness","Fitness room",["room","fitness"]),
  aliasDef("room-games","room-play","home","Sala gaming","Gaming room",["room","gaming"]),
  aliasDef("room-cellar","room-basement","home","Cantina vini","Wine cellar",["room","wine"]),
  aliasDef("room-loft","room-attic","home","Loft","Loft",["room","loft"]),
  aliasDef("room-guest-suite","room-guest","home","Suite ospiti","Guest suite",["room","guest"]),
  aliasDef("room-open-living","room-open-space","home","Living open space","Open living",["room","open","living"]),
  aliasDef("room-open-kitchen","room-open-space","home","Cucina open space","Open kitchen",["room","open","kitchen"]),
  aliasDef("room-landing","room-stairs","home","Pianerottolo","Landing",["room","stairs"]),
  aliasDef("heat-pump","ac","climate","Pompa di calore","Heat pump",["heat","pump"]),
  aliasDef("boiler","radiator","climate","Caldaia","Boiler",["boiler","heat"]),
  aliasDef("water-heater","thermometer","climate","Scaldabagno","Water heater",["water","heater"]),
  aliasDef("towel-warmer","radiator","climate","Scaldasalviette","Towel warmer",["radiator","bathroom"]),
  aliasDef("fireplace","flame","climate","Camino","Fireplace",["fireplace","heat"]),
  aliasDef("pellet-stove","flame","climate","Stufa pellet","Pellet stove",["pellet","stove"]),
  aliasDef("underfloor-zone","floor-heat","climate","Zona pavimento","Floor heating zone",["floor","zone"]),
  aliasDef("hvac-zone","thermostat","climate","Zona HVAC","HVAC zone",["hvac","zone"]),
  aliasDef("ventilation","fan","climate","Ventilazione","Ventilation",["ventilation","fan"]),
  aliasDef("erv","fan","climate","Recuperatore aria","Energy recovery ventilator",["erv","ventilation"]),
  aliasDef("air-extractor","fan","climate","Aspiratore aria","Extractor fan",["extractor","fan"]),
  aliasDef("air-sensor","air-quality","climate","Sensore aria","Air sensor",["air","sensor"]),
  aliasDef("co2-sensor","air-quality","climate","Sensore CO₂","CO2 sensor",["co2","sensor"]),
  aliasDef("pm25-sensor","air-quality","climate","Sensore PM2.5","PM2.5 sensor",["pm25","air"]),
  aliasDef("voc-sensor","air-quality","climate","Sensore VOC","VOC sensor",["voc","air"]),
  aliasDef("humidity-sensor","droplet","climate","Sensore umidità","Humidity sensor",["humidity","sensor"]),
  aliasDef("dehumidifier-smart","dehumidifier","climate","Deumidificatore smart","Smart dehumidifier",["dehumidifier","smart"]),
  aliasDef("humidifier-smart","humidifier","climate","Umidificatore smart","Smart humidifier",["humidifier","smart"]),
  aliasDef("purifier-hepa","air-purifier","climate","Purificatore HEPA","HEPA purifier",["hepa","purifier"]),
  aliasDef("door-sensor","contact","security","Sensore porta","Door sensor",["door","contact"]),
  aliasDef("window-sensor","contact","security","Sensore finestra","Window sensor",["window","contact"]),
  aliasDef("garage-sensor","contact","security","Sensore garage","Garage sensor",["garage","contact"]),
  aliasDef("gate-sensor","contact","security","Sensore cancello","Gate sensor",["gate","contact"]),
  aliasDef("vibration-sensor","sensor","security","Sensore vibrazione","Vibration sensor",["vibration","sensor"]),
  aliasDef("tilt-sensor","sensor","security","Sensore inclinazione","Tilt sensor",["tilt","sensor"]),
  aliasDef("lux-sensor","sun","security","Sensore luminosità","Illuminance sensor",["lux","light"]),
  aliasDef("occupancy-sensor","presence","security","Sensore occupazione","Occupancy sensor",["occupancy","presence"]),
  aliasDef("mmwave-sensor","sensor","security","Sensore mmWave","mmWave sensor",["mmwave","presence"]),
  aliasDef("pir-sensor","motion","security","Sensore PIR","PIR sensor",["pir","motion"]),
  aliasDef("alarm-keypad","lock","security","Tastiera allarme","Alarm keypad",["alarm","keypad"]),
  aliasDef("panic-button","switch","security","Pulsante emergenza","Panic button",["panic","button"]),
  aliasDef("key-fob","remote","security","Telecomando allarme","Alarm key fob",["keyfob","alarm"]),
  aliasDef("indoor-camera","camera","security","Camera interna","Indoor camera",["indoor","camera"]),
  aliasDef("outdoor-camera","camera","security","Camera esterna","Outdoor camera",["outdoor","camera"]),
  aliasDef("floodlight-camera","outdoor-wall","security","Camera con faro","Floodlight camera",["camera","floodlight"]),
  aliasDef("baby-monitor","camera","security","Baby monitor","Baby monitor",["baby","camera"]),
  aliasDef("video-doorbell","doorbell","security","Campanello video","Video doorbell",["doorbell","video"]),
  aliasDef("intercom","doorbell","security","Citofono","Intercom",["intercom","citofono"]),
  aliasDef("mailbox-sensor","contact","security","Sensore cassetta posta","Mailbox sensor",["mailbox","sensor"]),
  aliasDef("safe","lock","security","Cassaforte","Safe",["safe","lock"]),
  aliasDef("water-leak-sensor","leak","security","Sensore perdita","Water leak sensor",["leak","sensor"]),
  aliasDef("flood-sensor","flood","security","Sensore allagamento","Flood sensor",["flood","sensor"]),
  aliasDef("smoke-detector","smoke","security","Rilevatore fumo","Smoke detector",["smoke","detector"]),
  aliasDef("co-detector","co","security","Rilevatore CO","CO detector",["co","detector"]),
  aliasDef("freezer","fridge","appliances","Congelatore","Freezer",["freezer","congelatore"]),
  aliasDef("wine-cooler","fridge","appliances","Cantinetta vini","Wine cooler",["wine","cooler"]),
  aliasDef("mini-fridge","fridge","appliances","Mini frigo","Mini fridge",["mini","fridge"]),
  aliasDef("washer-dryer","washer","appliances","Lavasciuga","Washer dryer",["washer","dryer"]),
  aliasDef("air-fryer","oven","appliances","Friggitrice ad aria","Air fryer",["air fryer"]),
  aliasDef("rice-cooker","stove","appliances","Cuociriso","Rice cooker",["rice","cooker"]),
  aliasDef("slow-cooker","stove","appliances","Slow cooker","Slow cooker",["slow","cooker"]),
  aliasDef("pressure-cooker","stove","appliances","Pentola a pressione","Pressure cooker",["pressure","cooker"]),
  aliasDef("blender","coffee","appliances","Frullatore","Blender",["blender"]),
  aliasDef("mixer","coffee","appliances","Impastatrice","Mixer",["mixer","kitchen"]),
  aliasDef("food-processor","coffee","appliances","Robot da cucina","Food processor",["food","processor"]),
  aliasDef("espresso-machine","coffee","appliances","Macchina espresso","Espresso machine",["espresso","coffee"]),
  aliasDef("coffee-grinder","coffee","appliances","Macinacaffè","Coffee grinder",["coffee","grinder"]),
  aliasDef("water-dispenser","faucet","appliances","Dispenser acqua","Water dispenser",["water","dispenser"]),
  aliasDef("ice-maker","snowflake","appliances","Macchina ghiaccio","Ice maker",["ice","maker"]),
  aliasDef("robot-mop","robot","appliances","Robot lavapavimenti","Robot mop",["robot","mop"]),
  aliasDef("robot-mower","robot","appliances","Robot tagliaerba","Robot mower",["robot","mower"]),
  aliasDef("hand-vacuum","vacuum","appliances","Aspirabriciole","Hand vacuum",["vacuum","hand"]),
  aliasDef("stick-vacuum","vacuum","appliances","Scopa elettrica","Stick vacuum",["vacuum","stick"]),
  aliasDef("steam-cleaner","vacuum","appliances","Pulitore a vapore","Steam cleaner",["steam","cleaner"]),
  aliasDef("sewing-machine","washer","appliances","Macchina da cucire","Sewing machine",["sewing"]),
  aliasDef("hair-dryer","fan","appliances","Asciugacapelli","Hair dryer",["hair","dryer"]),
  aliasDef("electric-blanket","floor-heat","appliances","Coperta elettrica","Electric blanket",["blanket","heat"]),
  aliasDef("water-softener","droplet","appliances","Addolcitore","Water softener",["water","softener"]),
  aliasDef("home-battery","battery","energy","Batteria casa","Home battery",["battery","home"]),
  aliasDef("solar-battery","battery-charge","energy","Batteria solare","Solar battery",["solar","battery"]),
  aliasDef("ups","battery","energy","UPS","UPS",["ups","battery"]),
  aliasDef("inverter","meter","energy","Inverter","Inverter",["inverter","solar"]),
  aliasDef("micro-inverter","meter","energy","Microinverter","Micro inverter",["micro","inverter"]),
  aliasDef("smart-meter","meter","energy","Smart meter","Smart meter",["smart","meter"]),
  aliasDef("power-meter","meter","energy","Misuratore energia","Power meter",["power","meter"]),
  aliasDef("grid","bolt","energy","Rete elettrica","Power grid",["grid","electric"]),
  aliasDef("electric-panel","meter","energy","Quadro elettrico","Electrical panel",["panel","electric"]),
  aliasDef("breaker","switch","energy","Magnetotermico","Circuit breaker",["breaker","electric"]),
  aliasDef("ev-charger-home","ev-charger","energy","Wallbox casa","Home EV charger",["ev","wallbox"]),
  aliasDef("ev-charger-public","ev-charger","energy","Colonnina EV","Public EV charger",["ev","charger"]),
  aliasDef("smart-socket-energy","outlet","energy","Presa con energia","Energy socket",["socket","energy"]),
  aliasDef("solar-roof","solar","energy","Fotovoltaico tetto","Rooftop solar",["solar","roof"]),
  aliasDef("solar-garden","solar","energy","Solare giardino","Garden solar",["solar","garden"]),
  aliasDef("electric-car","car","outdoor","Auto elettrica","Electric car",["ev","car"]),
  aliasDef("hybrid-car","car","outdoor","Auto ibrida","Hybrid car",["hybrid","car"]),
  aliasDef("motorcycle","scooter","outdoor","Moto","Motorcycle",["motorcycle","moto"]),
  aliasDef("e-bike","bike","outdoor","E-bike","E-bike",["electric","bike"]),
  aliasDef("cargo-bike","bike","outdoor","Cargo bike","Cargo bike",["cargo","bike"]),
  aliasDef("garden-mower","robot","outdoor","Tagliaerba","Lawn mower",["mower","garden"]),
  aliasDef("garden-robot","robot","outdoor","Robot giardino","Garden robot",["robot","garden"]),
  aliasDef("irrigation-zone","sprinkler","outdoor","Zona irrigazione","Irrigation zone",["irrigation","zone"]),
  aliasDef("water-valve","faucet","outdoor","Valvola acqua","Water valve",["valve","water"]),
  aliasDef("pool-pump","pool","outdoor","Pompa piscina","Pool pump",["pool","pump"]),
  aliasDef("pool-light","bulb","outdoor","Luce piscina","Pool light",["pool","light"]),
  aliasDef("hot-tub","bath","outdoor","Idromassaggio","Hot tub",["spa","hot tub"]),
  aliasDef("pergola","patio","outdoor","Pergola","Pergola",["pergola","patio"]),
  aliasDef("gazebo","patio","outdoor","Gazebo","Gazebo",["gazebo","garden"]),
  aliasDef("weather-station","weather","outdoor","Stazione meteo","Weather station",["weather","station"]),
  aliasDef("rain-gauge","rain","outdoor","Pluviometro","Rain gauge",["rain","gauge"]),
  aliasDef("wind-sensor","fan","outdoor","Sensore vento","Wind sensor",["wind","sensor"]),
  aliasDef("soil-sensor","sensor","outdoor","Sensore terreno","Soil sensor",["soil","sensor"]),
  aliasDef("garden-gate","gate","outdoor","Cancello giardino","Garden gate",["garden","gate"]),
  aliasDef("driveway-gate","gate","outdoor","Cancello carrabile","Driveway gate",["driveway","gate"]),
  aliasDef("garage-door","garage","outdoor","Porta garage","Garage door",["garage","door"]),
  aliasDef("parcel-box","room-pantry","outdoor","Box pacchi","Parcel box",["parcel","box"]),
];


const CATALOG_EXPANSION_ICON_DEFINITIONS: IconDefinition[] = [
  aliasDef("matter-bulb","bulb","lighting","Lampadina Matter","Matter bulb",["matter","bulb","lampadina"]),
  aliasDef("thread-bulb","bulb","lighting","Lampadina Thread","Thread bulb",["thread","bulb","lampadina"]),
  aliasDef("zigbee-bulb","bulb","lighting","Lampadina Zigbee","Zigbee bulb",["zigbee","bulb","lampadina"]),
  aliasDef("wifi-bulb","bulb","lighting","Lampadina Wi‑Fi","Wi‑Fi bulb",["wifi","bulb","lampadina"]),
  aliasDef("smart-filament","bulb-filament","lighting","Filamento smart","Smart filament",["filament","vintage","smart"]),
  aliasDef("candle-bulb","candle","lighting","Lampadina candela","Candle bulb",["candle","bulb","e14"]),
  aliasDef("globe-g125","bulb-globe","lighting","Globo G125","G125 globe",["globe","g125","bulb"]),
  aliasDef("gu53-spot","spotlight","lighting","Faretto GU5.3","GU5.3 spot",["gu53","spot","mr16"]),
  aliasDef("par16-spot","spotlight","lighting","Faretto PAR16","PAR16 spot",["par16","spot"]),
  aliasDef("recessed-downlight","ceiling-round","lighting","Downlight incasso","Recessed downlight",["recessed","downlight","ceiling"]),
  aliasDef("ceiling-panel","ceiling","lighting","Pannello soffitto","Ceiling panel",["panel","ceiling","light"]),
  aliasDef("linear-pendant","pendant","lighting","Sospensione lineare","Linear pendant",["linear","pendant"]),
  aliasDef("pendant-cluster-large","chandelier","lighting","Sospensione multipla","Pendant cluster",["cluster","pendant","chandelier"]),
  aliasDef("desk-reading-lamp","table-lamp","lighting","Lampada lettura","Reading lamp",["reading","desk","lamp"]),
  aliasDef("mirror-light","light-bar","lighting","Luce specchio","Mirror light",["mirror","bathroom","light"]),
  aliasDef("under-cabinet-light","light-strip","lighting","Luce sottopensile","Under-cabinet light",["cabinet","kitchen","strip"]),
  aliasDef("stair-light","wall-lamp","lighting","Segnapasso scale","Stair light",["stairs","step","light"]),
  aliasDef("porch-light","outdoor-wall","lighting","Luce portico","Porch light",["porch","outdoor","light"]),
  aliasDef("bticino-switch","switch","home","Interruttore BTicino","BTicino switch",["bticino","switch","myhome"]),
  aliasDef("smart-switch-1g","switch","home","Interruttore 1 tasto","1-gang smart switch",["switch","1gang","wall"]),
  aliasDef("smart-switch-2g","switch","home","Interruttore 2 tasti","2-gang smart switch",["switch","2gang","wall"]),
  aliasDef("smart-switch-3g","switch","home","Interruttore 3 tasti","3-gang smart switch",["switch","3gang","wall"]),
  aliasDef("smart-relay","switch","home","Relè smart","Smart relay",["relay","switch","smart"]),
  aliasDef("scene-button","switch","home","Pulsante scena","Scene button",["scene","button","switch"]),
  aliasDef("rotary-dimmer","dimmer","home","Dimmer rotativo","Rotary dimmer",["dimmer","rotary","light"]),
  aliasDef("usb-outlet","outlet","home","Presa USB","USB outlet",["usb","outlet","socket"]),
  aliasDef("power-strip","smart-plug","home","Ciabatta smart","Smart power strip",["power","strip","plug"]),
  aliasDef("blind-motor","blinds","home","Motore veneziana","Blind motor",["blind","motor","cover"]),
  aliasDef("shutter-motor","shutters","home","Motore tapparella","Shutter motor",["shutter","motor","cover"]),
  aliasDef("curtain-motor","curtains","home","Motore tenda","Curtain motor",["curtain","motor","cover"]),
  aliasDef("garage-opener","garage","home","Apriporta garage","Garage opener",["garage","opener","door"]),
  aliasDef("gate-opener","gate","home","Apricancello","Gate opener",["gate","opener"]),
  aliasDef("sliding-door","door-open","home","Porta scorrevole","Sliding door",["sliding","door"]),
  aliasDef("patio-door","door","home","Porta terrazzo","Patio door",["patio","door"]),
  aliasDef("skylight","window","home","Lucernario","Skylight",["skylight","window"]),
  aliasDef("standing-desk","desk","home","Scrivania regolabile","Standing desk",["standing","desk","office"]),
  aliasDef("room-thermostat","thermostat","climate","Termostato ambiente","Room thermostat",["room","thermostat","climate"]),
  aliasDef("smart-trv","radiator","climate","Testina termostatica","Smart TRV",["trv","radiator","valve"]),
  aliasDef("radiator-valve","radiator","climate","Valvola radiatore","Radiator valve",["radiator","valve"]),
  aliasDef("boiler-thermostat","thermostat","climate","Termostato caldaia","Boiler thermostat",["boiler","thermostat"]),
  aliasDef("fan-coil","fan","climate","Fan coil","Fan coil",["fan","coil","climate"]),
  aliasDef("split-ac","ac","climate","Climatizzatore split","Split AC",["split","ac","climate"]),
  aliasDef("ducted-ac","ac","climate","Clima canalizzato","Ducted AC",["ducted","ac","climate"]),
  aliasDef("portable-ac","ac","climate","Climatizzatore portatile","Portable AC",["portable","ac"]),
  aliasDef("air-source-heat-pump","snowflake","climate","Pompa di calore aria","Air-source heat pump",["heat","pump","air"]),
  aliasDef("heated-towel-rail","radiator","climate","Scaldasalviette","Heated towel rail",["towel","radiator","bathroom"]),
  aliasDef("pellet-fireplace","flame","climate","Stufa a pellet","Pellet stove",["pellet","stove","heat"]),
  aliasDef("pedestal-fan","fan","climate","Ventilatore a piantana","Pedestal fan",["fan","pedestal"]),
  aliasDef("bathroom-extractor","fan","climate","Aspiratore bagno","Bathroom extractor",["fan","bathroom","extractor"]),
  aliasDef("hepa-purifier","air-purifier","climate","Purificatore HEPA","HEPA purifier",["hepa","air","purifier"]),
  aliasDef("co2-monitor","air-quality","climate","Monitor CO₂","CO₂ monitor",["co2","air","quality"]),
  aliasDef("door-contact-pro","contact","security","Sensore porta","Door contact",["door","contact","sensor"]),
  aliasDef("window-contact-pro","contact","security","Sensore finestra","Window contact",["window","contact","sensor"]),
  aliasDef("pir-motion","motion","security","Sensore PIR","PIR motion sensor",["pir","motion","sensor"]),
  aliasDef("mmwave-presence","presence","security","Presenza mmWave","mmWave presence",["mmwave","presence","sensor"]),
  aliasDef("room-occupancy","presence","security","Occupazione stanza","Room occupancy",["occupancy","room","presence"]),
  aliasDef("vibration-detector","sensor","security","Sensore vibrazione","Vibration detector",["vibration","sensor"]),
  aliasDef("tilt-detector","sensor","security","Sensore inclinazione","Tilt detector",["tilt","sensor"]),
  aliasDef("security-keypad","lock","security","Tastiera allarme","Alarm keypad",["alarm","keypad","security"]),
  aliasDef("alarm-fob","shield","security","Telecomando allarme","Alarm key fob",["alarm","fob","security"]),
  aliasDef("emergency-button","siren","security","Pulsante emergenza","Emergency button",["panic","emergency","button"]),
  aliasDef("smart-deadbolt","lock","security","Catenaccio smart","Smart deadbolt",["deadbolt","lock","smart"]),
  aliasDef("garage-contact","contact","security","Sensore garage","Garage contact",["garage","contact"]),
  aliasDef("camera-indoor-pro","camera","security","Telecamera interna","Indoor camera",["camera","indoor"]),
  aliasDef("camera-outdoor-pro","camera","security","Telecamera esterna","Outdoor camera",["camera","outdoor"]),
  aliasDef("camera-floodlight-pro","camera","security","Telecamera con faro","Floodlight camera",["camera","floodlight"]),
  aliasDef("oled-tv","tv","media","TV OLED","OLED TV",["oled","tv","television"]),
  aliasDef("mini-led-tv","tv","media","TV Mini‑LED","Mini-LED TV",["mini-led","tv"]),
  aliasDef("projector-screen","projector","media","Schermo proiettore","Projector screen",["projector","screen","cinema"]),
  aliasDef("stereo-speaker","speaker","media","Diffusore stereo","Stereo speaker",["stereo","speaker"]),
  aliasDef("bass-subwoofer","speaker","media","Subwoofer","Subwoofer",["subwoofer","bass","speaker"]),
  aliasDef("av-receiver","soundbar","media","Ricevitore AV","AV receiver",["av","receiver","audio"]),
  aliasDef("audio-amplifier","soundbar","media","Amplificatore","Audio amplifier",["amplifier","audio"]),
  aliasDef("vinyl-player","music","media","Giradischi","Turntable",["vinyl","turntable","music"]),
  aliasDef("network-streamer","music","media","Streamer audio","Network streamer",["streamer","audio","network"]),
  aliasDef("living-room-console","gamepad","media","Console da salotto","Game console",["console","game","tv"]),
  aliasDef("portable-game-console","gamepad","media","Console portatile","Handheld console",["handheld","console","game"]),
  aliasDef("mesh-router","router","media","Router mesh","Mesh router",["mesh","router","wifi"]),
  aliasDef("mesh-node","router","media","Nodo mesh","Mesh node",["mesh","node","wifi"]),
  aliasDef("nas-server","router","media","NAS","NAS server",["nas","server","network"]),
  aliasDef("ultrawide-monitor","monitor","media","Monitor ultrawide","Ultrawide monitor",["ultrawide","monitor"]),
  aliasDef("narwal-flow","robot","appliances","Narwal Flow","Narwal Flow",["narwal","flow","robot","vacuum"]),
  aliasDef("robot-vacuum-mop","robot","appliances","Robot aspira e lava","Robot vacuum & mop",["robot","vacuum","mop"]),
  aliasDef("cordless-vacuum","vacuum","appliances","Aspirapolvere cordless","Cordless vacuum",["cordless","vacuum"]),
  aliasDef("chest-freezer","fridge","appliances","Congelatore a pozzo","Chest freezer",["freezer","chest"]),
  aliasDef("beverage-wine-cooler","fridge","appliances","Cantinetta bevande","Beverage cooler",["wine","beverage","cooler"]),
  aliasDef("combo-washer-dryer","washer","appliances","Lavasciuga","Washer-dryer combo",["washer","dryer","combo"]),
  aliasDef("steam-oven","oven","appliances","Forno a vapore","Steam oven",["steam","oven"]),
  aliasDef("induction-cooktop","stove","appliances","Piano a induzione","Induction cooktop",["induction","cooktop"]),
  aliasDef("countertop-air-fryer","oven","appliances","Friggitrice ad aria","Air fryer",["air","fryer","oven"]),
  aliasDef("stand-mixer","coffee","appliances","Planetaria","Stand mixer",["mixer","kitchen"]),
  aliasDef("smart-rice-cooker","stove","appliances","Cuociriso","Rice cooker",["rice","cooker"]),
  aliasDef("smart-slow-cooker","stove","appliances","Slow cooker","Slow cooker",["slow","cooker"]),
  aliasDef("sous-vide","stove","appliances","Sous-vide","Sous-vide",["sous","vide","cooker"]),
  aliasDef("water-filter","faucet","appliances","Filtro acqua","Water filter",["water","filter"]),
  aliasDef("ice-dispenser","snowflake","appliances","Dispenser ghiaccio","Ice dispenser",["ice","dispenser"]),
  aliasDef("smart-kettle","kettle","appliances","Bollitore smart","Smart kettle",["smart","kettle"]),
  aliasDef("smart-toaster","toaster","appliances","Tostapane smart","Smart toaster",["smart","toaster"]),
  aliasDef("smart-coffee","coffee","appliances","Macchina caffè smart","Smart coffee machine",["smart","coffee"]),
  aliasDef("grid-meter","meter","energy","Contatore rete","Grid meter",["grid","meter","energy"]),
  aliasDef("solar-array","solar","energy","Campo fotovoltaico","Solar array",["solar","array"]),
  aliasDef("string-inverter","meter","energy","Inverter di stringa","String inverter",["string","inverter","solar"]),
  aliasDef("battery-module","battery","energy","Modulo batteria","Battery module",["battery","module"]),
  aliasDef("home-ups","battery","energy","UPS casa","Home UPS",["ups","home","battery"]),
  aliasDef("transfer-switch","switch","energy","Commutatore rete","Transfer switch",["transfer","switch","grid"]),
  aliasDef("power-monitor","meter","energy","Monitor potenza","Power monitor",["power","monitor","energy"]),
  aliasDef("current-clamp","meter","energy","Pinza amperometrica","Current clamp",["current","clamp","meter"]),
  aliasDef("voltage-sensor","bolt","energy","Sensore tensione","Voltage sensor",["voltage","sensor"]),
  aliasDef("smart-breaker","switch","energy","Interruttore smart quadro","Smart breaker",["breaker","smart","panel"]),
  aliasDef("energy-dashboard","meter","energy","Dashboard energia","Energy dashboard",["energy","dashboard"]),
  aliasDef("ev-wallbox","ev-charger","energy","Wallbox EV","EV wallbox",["ev","wallbox","charger"]),
  aliasDef("v2h-charger","ev-charger","energy","Carica V2H","V2H charger",["v2h","ev","charger"]),
  aliasDef("v2g-charger","ev-charger","energy","Carica V2G","V2G charger",["v2g","ev","charger"]),
  aliasDef("backup-generator","generator","energy","Generatore backup","Backup generator",["backup","generator"]),
  aliasDef("electric-suv","car","outdoor","SUV elettrico","Electric SUV",["ev","suv","car"]),
  aliasDef("city-scooter","scooter","outdoor","Scooter urbano","City scooter",["city","scooter"]),
  aliasDef("electric-scooter","scooter","outdoor","Monopattino elettrico","Electric scooter",["electric","scooter"]),
  aliasDef("commuter-bike","bike","outdoor","Bici urbana","Commuter bike",["commuter","bike"]),
  aliasDef("garden-mower-manual","robot","outdoor","Tagliaerba","Lawn mower",["mower","garden"]),
  aliasDef("drip-irrigation","sprinkler","outdoor","Irrigazione a goccia","Drip irrigation",["drip","irrigation"]),
  aliasDef("garden-valve","faucet","outdoor","Valvola giardino","Garden valve",["garden","valve","water"]),
  aliasDef("pool-filter","pool","outdoor","Filtro piscina","Pool filter",["pool","filter"]),
  aliasDef("pool-heater","flame","outdoor","Riscaldamento piscina","Pool heater",["pool","heater"]),
  aliasDef("greenhouse","patio","outdoor","Serra","Greenhouse",["greenhouse","garden"]),
  aliasDef("outdoor-socket","outlet","outdoor","Presa esterna","Outdoor socket",["outdoor","socket"]),
  aliasDef("fountain","faucet","outdoor","Fontana","Fountain",["fountain","water"]),
  aliasDef("awning-motor","awning","outdoor","Motore tenda esterna","Awning motor",["awning","motor"]),
  aliasDef("pergola-louver","patio","outdoor","Pergola bioclimatica","Louvered pergola",["pergola","louver"]),
  aliasDef("driveway-sensor","sensor","outdoor","Sensore vialetto","Driveway sensor",["driveway","sensor"]),
  aliasDef("smart-mailbox-sensor","contact","outdoor","Sensore cassetta postale","Mailbox sensor",["mailbox","sensor"]),
];

const ALL_ICON_DEFINITIONS: IconDefinition[] = [...SOURCE_ICON_DEFINITIONS, ...SEMANTIC_ICON_DEFINITIONS, ...CATALOG_EXPANSION_ICON_DEFINITIONS];

export const ICON_OPTIONS: IconOption[] = ALL_ICON_DEFINITIONS.map(({ glyph: _glyph, ...option }) => option);
const ICON_GLYPHS = Object.fromEntries(ALL_ICON_DEFINITIONS.map(({ key, glyph }) => [key, glyph])) as Record<string, ReactNode>;

const IconOverrideContext = createContext<IconOverrideMap>({});

export function EntityIconOverrideProvider({ value, children }: { value: IconOverrideMap; children: ReactNode }) {
  return <IconOverrideContext.Provider value={value}>{children}</IconOverrideContext.Provider>;
}

export function useEntityIconOverrides() {
  return useContext(IconOverrideContext);
}

function Glyph({ children }: { children: ReactNode }) {
  return <svg viewBox="0 0 24 24" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{children}</g></svg>;
}

export function renderEntityOverrideIcon(key?: string | null): ReactNode | null {
  const glyph = key ? ICON_GLYPHS[key] : null;
  return glyph ? <Glyph>{glyph}</Glyph> : null;
}

export function OverrideIcon({ targetId, fallback }: { targetId: string; fallback: ReactNode }) {
  const overrides = useEntityIconOverrides();
  return <>{renderEntityOverrideIcon(overrides[targetId]) ?? fallback}</>;
}

export function EntityIcon({ entityId, fallback }: { entityId: string; fallback: ReactNode }) {
  return <OverrideIcon targetId={entityId} fallback={fallback} />;
}

export function RoomOverrideIcon({ areaId, fallback }: { areaId: string; fallback: ReactNode }) {
  return <OverrideIcon targetId={`area:${areaId}`} fallback={fallback} />;
}
